### ISSUE TITLE
Problem with "__dmk_proc"

### ISSUE THREAD

**Issue by emilitow** [piteren/pypoks#11]
Hi, I was trying to run your function "run_human_game.py" with pretrained models, but when I executed it, an error popped up that I don't know how to solve. It's related to something called '__dmk_proc' (see picture below).

![image](https://user-images.githubusercontent.com/127898081/225137164-276ff89a-d865-4d0c-9690-469d05080dd3.png)

Thanks in advance for your help.

Also, thank you for sharing this project. It seems very interesting. Congratulations!

**Comment by piteren** [comment]
Hi,
Sorry for my late answer. I think this error is caused by outdated pretrained models.
I will update pretrained models soon to the last master commit, since I have made many updates recently, but for now you can check:
this commit: dc7bdf12
and those models: https://drive.google.com/file/d/1RAurtcobSXB8sKfbX96nWZGFD6EEakji/view?usp=sharing
- should work together - I have checked now.

I will message you when I update to the newest ones.
Feel free if you have any questions.
Regards.
Piotr

**Comment by phanbin777** [comment]
Hi Piteren and Emilitow
I got the same error. Have you fixed it yet?
Looks like it's no longer available "https://drive.google.com/file/d/1RAurtcobSXB8sKfbX96nWZGFD6EEakji/view?usp=sharing"
![image](https://github.com/piteren/pypoks/assets/25605681/e09eb572-e87d-4d4e-917f-fcac87c456a8)

**Comment by piteren** [comment]
Hi,
already fixed this, please checkout from master,
and if you want to use pretrained agents use link from the readme.

**Comment by phanbin777** [comment]
Hi,
Thank you very much, the above error has been resolved.
I keep getting new bug

**Comment by piteren** [comment]
I have not such error on linux, maybe it is something windows / multiprocessing related. I cannot help here.

**Comment by phanbin777** [comment]
Same in Linux

**Comment by piteren** [comment]
I cannot replicate the the error.
I run succesfully with PyCharm and in pure linux terminal.
Recently I have run this project on clear linux installation without such issue.

What linux, virtualenv do you use?
I think that it is something "environment" related, not the project itself. The problem is known for some users in other projects:
I would love to help, but cannot without replicating.

[on stackoverflow](https://stackoverflow.com/questions/1412787/picklingerror-cant-pickle-class-decimal-decimal-its-not-the-same-object)
[on medium](https://medium.com/devopss-hole/python-multiprocessing-pickle-issue-e2d35ccf96a9)

![Screenshot from 2024-03-03 12-22-26](https://github.com/piteren/pypoks/assets/34244544/742ddc8b-b1fe-47b8-a1b9-871e3928a51d)

**Comment by phanbin777** [comment]
Thank you very much. I have ruled out the possibility of a project problem. I tried reinstalling the project on pure Linux again.

**Comment by phanbin777** [comment]
Thank you very much for your support. I successfully launched it on Ubuntu 22.04 and Python 3.10.8
![image](https://github.com/piteren/pypoks/assets/25605681/a491de88-a90d-4973-b9d4-12be1e2650bc)
